apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod 
spec:
  containers:
  - image: takytaky/app:v1
    name: emptydir-container 
    volumeMounts:
    - mountPath: /cache
      name: emptydir-volume
  volumes:
  - name: emptydir-volume
    emptyDir: {}
