kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-label-ssd
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Mi
  storageClassName: manual
  selector:
    matchLabels:
      type: ssd
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-label-hdd
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Mi
  storageClassName: manual
  selector:
    matchLabels:
      type: hdd
