apiVersion: v1
kind: Pod
metadata:
  name: app-env
  labels:
    app: app-env
spec:
  containers:
  - name: container-env
    image: takytaky/app:v1
    ports:
    - containerPort: 80
    env:
    - name: ENV01
      value: "value01"
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: container-env
          resource: requests.cpu
    - name: CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: container-env
          resource: limits.cpu          
