apiVersion: v1
kind: ServiceAccount
metadata: 
  name: yumi
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: yumi
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-read-role
  apiGroup: rbac.authorization.k8s.io
