apiVersion: v1
kind: PersistentVolume     
metadata:
  name: pv-nfs
  labels:
    storage: pv-nfs
spec:
  capacity:                
    storage: 256Mi           
  accessModes:             
    - ReadWriteMany        
  volumeMode: Filesystem   
  persistentVolumeReclaimPolicy: Delete
  nfs:             
    server: 192.168.137.100
    path: /k8s_share

